"""Assessment-order drafting routes (BharatTax AO-side engine). Officer-scoped;
mirrors the appeals routes — reuses JWT/seat auth, MinIO storage, PDF extraction,
Celery and corpus-grounded drafting, from the Assessing Officer's perspective."""
from __future__ import annotations

import json
import logging
import mimetypes
from datetime import datetime, timezone

log = logging.getLogger("assessment")

from fastapi import APIRouter, Depends, File, HTTPException, Request, UploadFile, status
from fastapi.responses import Response
from pydantic import BaseModel
from sqlalchemy import func, select, desc
from sqlalchemy.orm import Session

from app.api.deps import Principal, client_meta, get_principal
from app.services.quota import require_quota
from app.core.db import get_db
from app.models.assessment import (
    AssessmentCase, AssessmentDocument, AssessmentOutput, AssessmentRun,
)
from app.models.enums import Role
from app.models.org import User
from app.services import audit
from app.services import assessment_draft as svc
from app.services.appeal_export import build_order_docx
from app.services.storage import put_bytes, get_bytes
from app.services import capture
from app.ingestion.extract import extract_text

router = APIRouter(prefix="/assessment", tags=["assessment"])

ALLOWED_UPLOAD_EXTENSIONS = {".pdf", ".docx", ".txt", ".html", ".htm"}

_BANNER = "DRAFT ASSESSMENT ORDER"
_SUBTITLE_PREFIX = "Assessment u/s"
_FOOTER = (
    "Draft generated by BharatTax for the Assessing Officer to apply independent "
    "mind and finalise. Verify every citation and figure against the cited source."
)


class CaseCreate(BaseModel):
    title: str
    assessment_year: str | None = None
    pan: str | None = None
    section: str | None = None


class CasePatch(BaseModel):
    title: str | None = None
    assessment_year: str | None = None
    pan: str | None = None
    section: str | None = None


class OutputEdit(BaseModel):
    content: str


def _get_case(db: Session, user: User, cid) -> AssessmentCase:
    """Resolve a case by opaque slug or numeric id, enforcing access control."""
    case: AssessmentCase | None = None
    if isinstance(cid, int):
        case = db.get(AssessmentCase, cid)
    elif isinstance(cid, str):
        s = cid.strip()
        if s.isdigit():
            case = db.get(AssessmentCase, int(s))
        else:
            case = db.scalar(select(AssessmentCase).where(AssessmentCase.slug == s))
    if not case:
        raise HTTPException(404, "Case not found")
    if case.owner_user_id == user.id or user.role == Role.super_admin:
        return case
    if user.role == Role.wing_admin and case.wing_id == user.wing_id:
        return case
    raise HTTPException(status.HTTP_403_FORBIDDEN, "Not authorised for this case")


def _case_out(c: AssessmentCase) -> dict:
    return {"id": c.id, "slug": c.slug, "title": c.title,
            "assessment_year": c.assessment_year, "pan": c.pan,
            "section": c.section, "status": c.status, "owner_user_id": c.owner_user_id,
            "created_at": c.created_at.isoformat() if c.created_at else None}


def _latest_run(db: Session, cid: int) -> AssessmentRun | None:
    return db.scalar(select(AssessmentRun).where(AssessmentRun.case_id == cid)
                     .order_by(desc(AssessmentRun.id)).limit(1))


def _run_out(r: AssessmentRun) -> dict:
    return {"id": r.id, "case_id": r.case_id, "status": r.status, "progress": r.progress,
            "provider": r.provider, "model": r.model, "error": r.error}


def _out(o: AssessmentOutput) -> dict:
    return {"id": o.id, "kind": o.kind, "seq": o.seq, "label": o.label, "content": o.content,
            "citations": o.citations or [], "edited": o.edited, "version": o.version}


def _latest_outputs(db: Session, run_id: int) -> list[AssessmentOutput]:
    best: dict[tuple, AssessmentOutput] = {}
    for o in db.scalars(select(AssessmentOutput).where(AssessmentOutput.run_id == run_id)):
        key = (o.kind, o.seq)
        if key not in best or o.version > best[key].version:
            best[key] = o
    return list(best.values())


# --- cases ---
@router.post("/cases")
def create_case(body: CaseCreate, p: Principal = Depends(get_principal), db: Session = Depends(get_db)):
    import uuid as _uuid
    slug = _uuid.uuid4().hex
    c = AssessmentCase(owner_user_id=p.user.id, wing_id=p.user.wing_id, title=body.title,
                       assessment_year=body.assessment_year, pan=body.pan,
                       section=body.section, slug=slug)
    db.add(c); db.commit(); db.refresh(c)
    return _case_out(c)


@router.get("/cases")
def list_cases(p: Principal = Depends(get_principal), db: Session = Depends(get_db)):
    q = select(AssessmentCase).order_by(desc(AssessmentCase.updated_at))
    if p.user.role == Role.super_admin:
        pass
    elif p.user.role == Role.wing_admin:
        q = q.where(AssessmentCase.wing_id == p.user.wing_id)
    else:
        q = q.where(AssessmentCase.owner_user_id == p.user.id)

    # Self-heal a stranded 'running' badge whose latest run is already terminal.
    stuck = list(db.scalars(
        select(AssessmentCase.id).where(
            AssessmentCase.status == "running",
            *([] if p.user.role == Role.super_admin
              else [AssessmentCase.wing_id == p.user.wing_id] if p.user.role == Role.wing_admin
              else [AssessmentCase.owner_user_id == p.user.id]),
        )
    ))
    if stuck:
        from sqlalchemy import text as _sql_text
        try:
            db.execute(_sql_text("""
                UPDATE assessment_cases c
                   SET status = CASE
                                  WHEN r.status = 'done'  THEN 'ready'
                                  WHEN r.status = 'error' THEN 'error'
                                  ELSE c.status
                                END
                  FROM (
                    SELECT DISTINCT ON (case_id) case_id, status
                      FROM assessment_runs
                      WHERE case_id = ANY(:ids)
                      ORDER BY case_id, id DESC
                  ) r
                 WHERE r.case_id = c.id
                   AND c.status = 'running'
                   AND r.status IN ('done', 'error')
            """), {"ids": stuck})
            db.commit()
        except Exception:
            db.rollback()

    return [_case_out(c) for c in db.scalars(q)]


@router.get("/cases/{cid}")
def get_case(cid: str, p: Principal = Depends(get_principal), db: Session = Depends(get_db)):
    case = _get_case(db, p.user, cid)
    return {**_case_out(case),
            "documents": [{"id": d.id, "filename": d.filename, "category": d.category, "pages": d.pages}
                          for d in case.documents]}


@router.patch("/cases/{cid}")
def patch_case(cid: str, body: CasePatch,
               p: Principal = Depends(get_principal),
               db: Session = Depends(get_db), request: Request = None):
    case = _get_case(db, p.user, cid)
    changed: list[str] = []
    if body.title is not None:
        title = (body.title or "").strip()
        if not title:
            raise HTTPException(400, "Title cannot be empty")
        if title != case.title:
            case.title = title
            changed.append("title")
    for attr, val in (("assessment_year", body.assessment_year), ("pan", body.pan), ("section", body.section)):
        if val is None:
            continue
        cleaned = val.strip() or None
        if attr == "pan" and cleaned:
            cleaned = cleaned.upper()
        if cleaned != getattr(case, attr):
            setattr(case, attr, cleaned)
            changed.append(attr)
    if changed:
        db.commit()
        audit.log_event(db, action="assessment.case.edit", user_id=p.user.id, wing_id=p.user.wing_id,
                        resource_type="assessment_case", resource_id=str(case.id),
                        query_text=",".join(changed), **client_meta(request))
    return {**_case_out(case),
            "documents": [{"id": d.id, "filename": d.filename, "category": d.category, "pages": d.pages}
                          for d in case.documents]}


@router.delete("/cases/{cid}", status_code=204)
def delete_case(cid: str, p: Principal = Depends(get_principal),
                db: Session = Depends(get_db), request: Request = None):
    case = _get_case(db, p.user, cid)
    case_id_int = case.id

    active = db.scalar(select(AssessmentRun).where(AssessmentRun.case_id == case.id)
                       .order_by(desc(AssessmentRun.id)).limit(1))
    if active and active.status in ("queued", "running"):
        _cancel_run(db, active, user_id=p.user.id)

    for d in list(case.documents):
        if not d.minio_key:
            continue
        try:
            from app.services.storage import remove_object
            remove_object(d.minio_key)
        except Exception as e:
            log.warning("storage delete failed for %s: %s", d.minio_key, e)

    case = db.get(AssessmentCase, case_id_int)
    if case is None:
        return None
    case_title = case.title
    db.delete(case)
    db.commit()
    audit.log_event(db, action="assessment.case.delete", user_id=p.user.id, wing_id=p.user.wing_id,
                    resource_type="assessment_case", resource_id=str(case_id_int),
                    query_text=case_title, **client_meta(request))
    return None


# --- documents ---
@router.post("/cases/{cid}/documents")
async def upload_docs(cid: str, files: list[UploadFile] = File(...),
                      p: Principal = Depends(get_principal),
                      _quota: Principal = Depends(require_quota),
                      db: Session = Depends(get_db), request: Request = None):
    case = _get_case(db, p.user, cid)
    added, skipped = [], []
    for f in files:
        filename = f.filename or ""
        guessed_type, _ = mimetypes.guess_type(filename)
        ext = f".{filename.rsplit('.', 1)[1].lower()}" if "." in filename else ""
        if not filename or ext not in ALLOWED_UPLOAD_EXTENSIONS:
            skipped.append(filename or "(unnamed file)")
            continue
        raw = await f.read()
        content_type = f.content_type or guessed_type or "application/octet-stream"
        import hashlib as _hashlib
        sha256_hex = _hashlib.sha256(raw).hexdigest()
        key = f"assessment/case_{case.id}/{sha256_hex}{ext}"
        put_bytes(key, raw, content_type=content_type)
        try:
            text = extract_text(raw, content_type, filename=filename)
        except Exception:
            text = ""
        if not text.strip():
            prior = db.scalar(
                select(AssessmentDocument)
                .where(AssessmentDocument.sha256 == sha256_hex,
                       func.length(AssessmentDocument.text) > 100)
                .order_by(desc(AssessmentDocument.id)).limit(1)
            )
            if prior is not None:
                text = prior.text
        pages = text.count("\f") + 1 if ext == ".pdf" and text else 0
        doc = AssessmentDocument(case_id=case.id, filename=filename,
                                 category=svc.classify(filename, text),
                                 minio_key=key, text=text, pages=pages, sha256=sha256_hex)
        db.add(doc); added.append(doc)
    db.commit()
    present = {d.category for d in case.documents}
    audit.log_event(db, action="assessment.upload", user_id=p.user.id, wing_id=p.user.wing_id,
                    resource_type="assessment_case", resource_id=str(case.id), **client_meta(request))
    return {"documents": [{"id": d.id, "filename": d.filename, "category": d.category, "pages": d.pages}
                          for d in case.documents],
            "missing": [c for c in svc.EXPECTED if c not in present],
            "accepted_types": sorted(ALLOWED_UPLOAD_EXTENSIONS),
            "skipped": skipped}


@router.get("/cases/{cid}/documents/{did}/file")
def get_doc_file(cid: str, did: int, p: Principal = Depends(get_principal), db: Session = Depends(get_db)):
    case = _get_case(db, p.user, cid)
    doc = db.get(AssessmentDocument, did)
    if not doc or doc.case_id != case.id:
        raise HTTPException(404, "Not found")
    media_type = mimetypes.guess_type(doc.filename)[0] or "application/octet-stream"
    disposition = "inline" if media_type == "application/pdf" else "attachment"
    return Response(get_bytes(doc.minio_key), media_type=media_type,
                    headers={"Content-Disposition": f'{disposition}; filename="{doc.filename}"'})


class _DocCategoryUpdate(BaseModel):
    category: str


@router.put("/cases/{cid}/documents/{did}")
def update_doc_category(cid: str, did: int, body: _DocCategoryUpdate,
                        p: Principal = Depends(get_principal), db: Session = Depends(get_db)):
    case = _get_case(db, p.user, cid)
    doc = db.get(AssessmentDocument, did)
    if not doc or doc.case_id != case.id:
        raise HTTPException(404, "Not found")
    cat = (body.category or "").strip().lower()
    if cat not in svc.DOC_CATEGORIES:
        raise HTTPException(400, f"Unknown category. Allowed: {', '.join(svc.DOC_CATEGORIES)}")
    doc.category = cat
    db.commit()
    present = {d.category for d in case.documents}
    return {"id": doc.id, "filename": doc.filename, "category": doc.category, "pages": doc.pages,
            "missing": [c for c in svc.EXPECTED if c not in present]}


@router.delete("/cases/{cid}/documents/{did}")
def delete_doc(cid: str, did: int, p: Principal = Depends(get_principal),
               db: Session = Depends(get_db), request: Request = None):
    case = _get_case(db, p.user, cid)
    doc = db.get(AssessmentDocument, did)
    if not doc or doc.case_id != case.id:
        raise HTTPException(404, "Not found")
    if doc.minio_key:
        shared = db.scalar(select(func.count()).select_from(AssessmentDocument)
                           .where(AssessmentDocument.minio_key == doc.minio_key,
                                  AssessmentDocument.id != doc.id))
        if not shared:
            try:
                from app.services.storage import remove_object
                remove_object(doc.minio_key)
            except Exception as e:
                log.warning("storage delete failed for %s: %s", doc.minio_key, e)
    filename = doc.filename
    db.delete(doc)
    db.commit()
    db.refresh(case)
    audit.log_event(db, action="assessment.doc.delete", user_id=p.user.id, wing_id=p.user.wing_id,
                    resource_type="assessment_document", resource_id=str(did),
                    query_text=filename, **client_meta(request))
    present = {d.category for d in case.documents}
    return {"deleted_id": did, "filename": filename,
            "missing": [c for c in svc.EXPECTED if c not in present]}


# --- run / outputs ---
@router.post("/cases/{cid}/run")
def start_run(cid: str, p: Principal = Depends(get_principal),
              _quota: Principal = Depends(require_quota),
              db: Session = Depends(get_db), request: Request = None):
    case = _get_case(db, p.user, cid)
    if not case.documents:
        raise HTTPException(400, "Upload documents before running")
    run = AssessmentRun(case_id=case.id, created_by=p.user.id, status="queued")
    db.add(run); db.commit(); db.refresh(run)
    from app.ingestion.tasks import run_assessment_case
    async_result = run_assessment_case.delay(run.id)
    run.task_id = async_result.id
    db.commit()
    audit.log_event(db, action="assessment.run", user_id=p.user.id, wing_id=p.user.wing_id,
                    resource_type="assessment_case", resource_id=str(case.id), **client_meta(request))
    return _run_out(run)


def _cancel_run(db: Session, run: AssessmentRun, *, user_id: int) -> None:
    if run.status not in ("queued", "running"):
        return
    if run.task_id:
        try:
            from app.ingestion.tasks import celery_app
            celery_app.control.revoke(run.task_id, terminate=True, signal="SIGTERM")
        except Exception:
            pass
    from sqlalchemy import update as _sql_update
    db.execute(_sql_update(AssessmentRun).where(AssessmentRun.id == run.id)
               .values(status="error", error=f"Cancelled by user (uid={user_id})",
                       finished_at=datetime.now(timezone.utc)))
    db.execute(_sql_update(AssessmentCase).where(AssessmentCase.id == run.case_id,
                                                 AssessmentCase.status == "running")
               .values(status="error"))
    db.commit()
    db.expire_all()


@router.post("/runs/{rid}/cancel")
def cancel_run(rid: int, p: Principal = Depends(get_principal),
               db: Session = Depends(get_db), request: Request = None):
    run = db.get(AssessmentRun, rid)
    if not run:
        raise HTTPException(404, "Run not found")
    _get_case(db, p.user, run.case_id)
    _cancel_run(db, run, user_id=p.user.id)
    audit.log_event(db, action="assessment.run.cancel", user_id=p.user.id, wing_id=p.user.wing_id,
                    resource_type="assessment_run", resource_id=str(rid), **client_meta(request))
    return _run_out(run)


@router.post("/cases/{cid}/stop")
def stop_case(cid: str, p: Principal = Depends(get_principal),
              db: Session = Depends(get_db), request: Request = None):
    from sqlalchemy import update as _sql_update
    case = _get_case(db, p.user, cid)
    run = _latest_run(db, case.id)
    if not run:
        db.execute(_sql_update(AssessmentCase).where(AssessmentCase.id == case.id,
                                                     AssessmentCase.status == "running")
                   .values(status="new"))
        db.commit()
        raise HTTPException(404, "No run to stop")
    if run.status not in ("queued", "running"):
        target = "ready" if run.status == "done" else "error"
        db.execute(_sql_update(AssessmentCase).where(AssessmentCase.id == case.id,
                                                     AssessmentCase.status == "running")
                   .values(status=target))
        db.commit()
        db.expire_all()
        return _run_out(run)
    _cancel_run(db, run, user_id=p.user.id)
    audit.log_event(db, action="assessment.case.stop", user_id=p.user.id, wing_id=p.user.wing_id,
                    resource_type="assessment_case", resource_id=str(cid), **client_meta(request))
    return _run_out(run)


@router.get("/runs/{rid}")
def get_run(rid: int, p: Principal = Depends(get_principal), db: Session = Depends(get_db)):
    run = db.get(AssessmentRun, rid)
    if not run:
        raise HTTPException(404, "Run not found")
    _get_case(db, p.user, run.case_id)
    return _run_out(run)


@router.get("/cases/{cid}/latest")
def latest(cid: str, p: Principal = Depends(get_principal), db: Session = Depends(get_db)):
    case = _get_case(db, p.user, cid)
    run = _latest_run(db, case.id)
    if not run:
        return {"run": None, "outputs": [], "issues": []}
    outs = _latest_outputs(db, run.id)
    issues = sorted([o for o in outs if o.kind == "issue"], key=lambda o: o.seq)
    return {"run": _run_out(run),
            "outputs": [_out(o) for o in outs if o.kind != "issue"],
            "issues": [_out(o) for o in issues]}


@router.put("/outputs/{oid}")
def edit_output(oid: int, body: OutputEdit, p: Principal = Depends(get_principal), db: Session = Depends(get_db)):
    o = db.get(AssessmentOutput, oid)
    if not o:
        raise HTTPException(404, "Output not found")
    run = db.get(AssessmentRun, o.run_id)
    if not run:
        raise HTTPException(404, "Run not found")
    _get_case(db, p.user, run.case_id)
    nxt = AssessmentOutput(run_id=o.run_id, kind=o.kind, seq=o.seq, label=o.label,
                           content=body.content, citations=o.citations, edited=True, version=o.version + 1)
    db.add(nxt); db.commit(); db.refresh(nxt)
    try:
        capture.log_event("gold_edit", task=f"assessment.edit.{o.kind}",
                          user_id=p.user.id, run_id=o.run_id,
                          context=o.content, response=body.content,
                          meta={"kind": o.kind, "seq": o.seq, "output_id": oid,
                                "new_output_id": nxt.id, "version": nxt.version})
    except Exception:
        pass
    return _out(nxt)


@router.post("/cases/{cid}/issues/{seq}/regenerate")
def regenerate(cid: str, seq: int, p: Principal = Depends(get_principal),
               _quota: Principal = Depends(require_quota), db: Session = Depends(get_db)):
    case = _get_case(db, p.user, cid)
    run = _latest_run(db, case.id)
    if not run:
        raise HTTPException(400, "Run the pipeline first")
    u = next((o for o in _latest_outputs(db, run.id) if o.kind == "understanding"), None)
    issues = (json.loads(u.content).get("issues") if u else None) or []
    if seq >= len(issues):
        raise HTTPException(404, "Issue not found")
    block, cites = svc.draft_issue(db, case, issues[seq])
    prev = list(db.scalars(select(AssessmentOutput).where(
        AssessmentOutput.run_id == run.id, AssessmentOutput.kind == "issue", AssessmentOutput.seq == seq)))
    ver = max([o.version for o in prev], default=0) + 1
    label = (issues[seq].get("issue") if isinstance(issues[seq], dict) else str(issues[seq])) or ""
    o = AssessmentOutput(run_id=run.id, kind="issue", seq=seq, label=label[:290],
                         content=block, citations=cites, version=ver)
    db.add(o); db.commit(); db.refresh(o)
    return _out(o)


@router.post("/cases/{cid}/reassemble")
def reassemble(cid: str, p: Principal = Depends(get_principal),
               _quota: Principal = Depends(require_quota), db: Session = Depends(get_db)):
    case = _get_case(db, p.user, cid)
    run = _latest_run(db, case.id)
    if not run:
        raise HTTPException(400, "Run the pipeline first")
    outs = _latest_outputs(db, run.id)
    u = next((o for o in outs if o.kind == "understanding"), None)
    understanding = json.loads(u.content) if u else {}
    issues = sorted([o for o in outs if o.kind == "issue"], key=lambda o: o.seq)
    blocks = [o.content for o in issues]
    comp = next((o for o in outs if o.kind == "computation"), None)
    order = svc.assemble(understanding, blocks, computation=(comp.content if comp else None))
    cur = list(db.scalars(select(AssessmentOutput).where(
        AssessmentOutput.run_id == run.id, AssessmentOutput.kind == "order")))
    ver = max([o.version for o in cur], default=0) + 1
    o = AssessmentOutput(run_id=run.id, kind="order", content=order, version=ver)
    db.add(o); db.commit(); db.refresh(o)
    return _out(o)


def _latest_order_for_case(db: Session, cid: int) -> AssessmentOutput | None:
    run = _latest_run(db, cid)
    if not run:
        return None
    return db.scalar(select(AssessmentOutput).where(
        AssessmentOutput.run_id == run.id, AssessmentOutput.kind == "order")
        .order_by(desc(AssessmentOutput.version)).limit(1))


@router.get("/cases/{cid}/export.docx")
def export_docx(cid: str, p: Principal = Depends(get_principal), db: Session = Depends(get_db)):
    case = _get_case(db, p.user, cid)
    order = _latest_order_for_case(db, case.id)
    if not order:
        raise HTTPException(404, "No draft yet — run the pipeline first")
    data = build_order_docx(
        case.title, order.content, pan=case.pan, assessment_year=case.assessment_year,
        section=case.section, banner_text=_BANNER, subtitle_prefix=_SUBTITLE_PREFIX, footer_text=_FOOTER,
    )
    return Response(content=data,
                    media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                    headers={"Content-Disposition": f'attachment; filename="assessment_order_case_{cid}.docx"'})
