"""Desktop-app session log.

The desktop client POSTs to /desktop/session/start on successful sign-in and
/desktop/session/end on sign-out (or app quit).  Admins use the resulting
list to see who is using the desktop app, how often, from which version and
IP, and what they did during the session.  Powers the "Desktop User Logs"
admin page.
"""
from __future__ import annotations

from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, Integer, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column

from app.core.db import Base


class DesktopSession(Base):
    __tablename__ = "desktop_sessions"

    id: Mapped[int] = mapped_column(primary_key=True)
    user_id: Mapped[int | None] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL"), nullable=True, index=True
    )
    # Opaque token generated by the desktop; identifies THIS launch across
    # heartbeats.  Not a security credential.
    session_token: Mapped[str] = mapped_column(String(64), unique=True, index=True)
    client_version: Mapped[str | None] = mapped_column(String(20), nullable=True)
    ip_address: Mapped[str | None] = mapped_column(String(64), nullable=True)
    user_agent: Mapped[str | None] = mapped_column(Text, nullable=True)
    started_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), index=True
    )
    # Populated on explicit sign-out.  NULL means the session is still
    # "open" (either still in use, or the client crashed without ending).
    ended_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    # Free-form last recorded action label ("case:opened", "draft:edited") —
    # helps admins triage without walking the audit log for every session.
    last_action: Mapped[str | None] = mapped_column(String(120), nullable=True)
    last_action_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    # Cheap counter of significant actions during the session so the admin
    # list can rank "busy" sessions without JOINing to audit_log.
    action_count: Mapped[int] = mapped_column(Integer, default=0)
