"""Pure-function tests for the assessment-order engine — the document
classifier, the order assembler and the DOCX exporter. No DB / no LLM."""
from app.services import assessment_draft as svc
from app.services.appeal_export import build_order_docx


def test_classify_return_variants():
    assert svc.classify("ITR-V_2022.pdf", "") == "return_of_income"
    assert svc.classify("ITR-3.pdf", "") == "return_of_income"
    assert svc.classify("x.pdf", "This is the Return of Income for AY 2022-23") == "return_of_income"


def test_classify_notices_and_reply():
    assert svc.classify("notice_143(2).pdf", "") == "notice_143_2"
    assert svc.classify("questionnaire_142(1).pdf", "") == "notice_142_1"
    assert svc.classify("reply.pdf", "") == "assessee_reply"


def test_classify_third_party_and_financials():
    assert svc.classify("AIS.pdf", "") == "third_party_info"
    assert svc.classify("form_26as.pdf", "") == "third_party_info"
    assert svc.classify("bank_statement.pdf", "") == "financials"


def test_classify_unknown_defaults_unclassified():
    assert svc.classify("misc.pdf", "nothing telltale here") == "unclassified"


def test_doc_categories_cover_expected():
    for cat in svc.EXPECTED:
        assert cat in svc.DOC_CATEGORIES


def test_assemble_builds_full_order():
    understanding = {
        "return_income": "Rs. 4,52,310",
        "issues": [
            {"issue": "Unexplained cash credit u/s 68", "query": "", "amount": "Rs. 12,00,000"},
            {"issue": "Disallowance u/s 14A", "query": "", "amount": ""},
        ],
    }
    blocks = [
        "The loan is unexplained. Accordingly, an addition of Rs. 12,00,000 is made u/s 68.",
        "The explanation is accepted and no addition is called for on this issue.",
    ]
    order = svc.assemble(understanding, blocks, intro="Intro para.",
                         computation="Returned income Rs. 4,52,310\nAdd: Rs. 12,00,000\nAssessed Rs. 16,52,310")
    assert "Intro para." in order
    assert "### Issue 1: Unexplained cash credit u/s 68" in order
    assert "### Issue 2: Disallowance u/s 14A" in order
    assert "### Computation of Total Income" in order
    assert "notice of demand u/s 156" in order.lower()


def test_assemble_without_intro_or_computation():
    order = svc.assemble({"issues": []}, ["Finding text."])
    assert "### Issue 1" in order
    # Closing directions are always appended.
    assert "234a" in order.lower()


def test_build_order_docx_assessment_variant():
    data = build_order_docx(
        "ABC Traders", "### Issue 1\n\n1. Facts.\n\nAddition of Rs. 5,00,000 u/s 68.",
        pan="AAAPL1234C", assessment_year="2022-23", section="143(3)",
        banner_text="DRAFT ASSESSMENT ORDER", subtitle_prefix="Assessment u/s",
        footer_text="Draft generated by BharatTax.",
    )
    # A valid .docx is a zip archive.
    assert data[:2] == b"PK"
    assert len(data) > 2000
