"""Render the draft appellate order to an editable .docx for the officer to finalise."""
from __future__ import annotations

import io
import re

from docx import Document as Docx
from docx.shared import Pt

_BOLD = re.compile(r"\*\*(.+?)\*\*")


def _strip(s: str) -> str:
    return _BOLD.sub(r"\1", s).strip()


def _inline(p, line: str) -> None:
    pos = 0
    for m in _BOLD.finditer(line):
        if m.start() > pos:
            p.add_run(line[pos:m.start()])
        p.add_run(m.group(1)).bold = True
        pos = m.end()
    if pos < len(line):
        p.add_run(line[pos:])


def build_order_docx(case_title: str, draft_text: str) -> bytes:
    doc = Docx()
    doc.add_heading("DRAFT APPELLATE ORDER", level=0)
    doc.add_paragraph().add_run(case_title or "").italic = True
    doc.add_paragraph("")
    for raw in (draft_text or "").split("\n"):
        line = raw.rstrip()
        if not line.strip():
            doc.add_paragraph("")
            continue
        m = re.match(r"^(#{1,4})\s+(.*)$", line)
        if m:
            doc.add_heading(_strip(m.group(2)), level=min(len(m.group(1)), 4))
            continue
        if re.match(r"^\s*[-*]\s+", line):
            doc.add_paragraph(_strip(re.sub(r"^\s*[-*]\s+", "", line)), style="List Bullet")
            continue
        _inline(doc.add_paragraph(), line)
    note = doc.add_paragraph()
    r = note.add_run("Draft generated by BharathTax for the Commissioner (Appeals) to apply independent "
                     "mind and finalise. Verify every citation against the cited source.")
    r.italic = True
    r.font.size = Pt(8)
    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()
